version: '3'
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.6.1
    ports:
      - '9090:9090'
    networks:
      - promnetwork
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    extra_hosts:
      - "docker_host_ip:$DOCKER_HOST_IP"

    # 設定リロードを有効にする
    # curl -X POST http://localhost:9090/-/reload
    # curlでエラーは出ないがscrape_interval変更が効いていないように見える
    # 再起動する方が確実
    # command: '--web.enable-lifecycle'

  grafana:
    container_name: grafana
    image: grafana/grafana:5.4.3
    ports:
      - '3000:3000'
    networks:
      - promnetwork

networks:
  promnetwork:
