version: '3'
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.6.1
    ports:
      - '9090:9090'
    networks:
      - promnetwork
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    extra_hosts:
      - "docker_host_ip:$DOCKER_HOST_IP"

networks:
  promnetwork:
