version: '3'
services:

  es_data0:
    container_name: es_data0
    build: .
    ports:
      - '9220:9200'
      - '9320:9300'
    networks:
      - esnetwork
    volumes:
      - ./es_data0_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es_data0_data:/usr/share/elasticsearch/data

  es_data1:
    container_name: es_data1
    build: .
    ports:
      - '9221:9200'
      - '9321:9300'
    networks:
      - esnetwork
    volumes:
      - ./es_data1_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es_data1_data:/usr/share/elasticsearch/data

  es_data2:
    container_name: es_data2
    build: .
    ports:
      - '9222:9200'
      - '9322:9300'
    networks:
      - esnetwork
    volumes:
      - ./es_data2_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es_data2_data:/usr/share/elasticsearch/data

  es_master0:
    container_name: es_master0
    build: .
    ports:
      - '9210:9200'
      - '9310:9300'
    networks:
      - esnetwork
    volumes:
      - ./es_master0_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es_master0_data:/usr/share/elasticsearch/data

  es_master1:
    container_name: es_master1
    build: .
    ports:
      - '9211:9200'
      - '9311:9300'
    networks:
      - esnetwork
    volumes:
      - ./es_master1_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es_master1_data:/usr/share/elasticsearch/data

  es_master2:
    container_name: es_master2
    build: .
    ports:
      - '9212:9200'
      - '9312:9300'
    networks:
      - esnetwork
    volumes:
      - ./es_master2_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es_master2_data:/usr/share/elasticsearch/data

  es_ingest0:
    container_name: es_ingest0
    build: .
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - esnetwork
    volumes:
      - ./es_ingest0_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es_ingest0_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:6.5.4
    ports:
      - '5601:5601'
    networks:
      - esnetwork
    volumes:
      - ./kibana_config/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  esnetwork:
