version: '3'
services:
  elasticsearch:
    build: .
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - esnetwork
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:6.5.4
    ports:
      - '5601:5601'
    networks:
      - esnetwork

networks:
  esnetwork:
