version: '3'
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
      - '50000:50000'
      - '30022:30022' # sshd
    networks:
      - jenkinsnw
    volumes:
      - ./jenkins_home:/var/jenkins_home

networks:
  jenkinsnw:
